### ISSUE TITLE
can't open device: No such file or directory

### ISSUE THREAD

**Issue by bk3a12** [antiprism/libu8g2arm#2]
Hi, I tried to your libu8g2arm library to compile example from yours using Nokia 5110 display on RP3b using HW SPI.
Compilation succeeded but running compiled binary showed up error 'can't open device: No such file or directory' Aborted.

Using example from [u8g2-arm-linux](https://github.com/wuhanstudio/u8g2-arm-linux/tree/master) was running well.

Can you please help to take a look?

![image](https://github.com/antiprism/libu8g2arm/assets/87455531/601a43bb-eda0-43ad-a608-10fa0ef2bc60)

**Comment by antiprism** [comment]
Hi

From a visual review, it looks like you are passing a CS pin number rather than the CS number itself, hence accessing an SPI device that doesn't exist (/dev/spidev0.8). If you are using pin 8 then I believe the CS value is 0.

Adrian.

**Comment by bk3a12** [comment]
Thanks for explanation. It is working now :)
